[settings]
# use uv for venv management when uv.lock is present
python.uv_venv_auto = true
# auto-trust mise.toml in these directories
trusted_config_paths = [
  "~/Developer/projex",
]
idiomatic_version_file_enable_tools = ["node"]

[tools]
node = "lts"
python = "3.13"
ruff = "latest"
terraform = "latest"
yarn = "4.9.2"
