# prefix (C-Space - least conflicting)
set -g prefix C-Space
unbind-key C-b
bind-key C-Space send-prefix

# essentials
set-window-option -g mode-keys vi
set-window-option -g pane-base-index 1
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g mouse on
set -g default-terminal "tmux-256color"
set -g history-limit 10000
set -g escape-time 0
set -s focus-events on
set -s extended-keys on
set -g automatic-rename on
set -g automatic-rename-format '#{b:pane_current_path}'

# clipboard (sync with system clipboard via pbcopy)
set -g set-clipboard on
bind-key c copy-mode
bind-key -n M-c copy-mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"

# status bar
set -g status-interval 1
set -g status-justify centre
set -g status-keys vi
set -g status-position bottom
set -g status-style bg=default
set -g status-left "#[fg=#242b38,bg=#ffcc66,bold] #S "
set -g status-left-length 40
set -g status-right-length 140
set -g window-status-format "#[fg=#5c6773] #I:#W "
set -g window-status-current-format "#[fg=#73d0ff,bold] #I:#W "
set -g status-right "#[fg=#d9d7ce,bg=#272d38] %d.%m.%Y #[fg=#242b38,bg=#ffcc66,bold] %a %H:%M:%S %Z "
set -g pane-border-style "fg=#1f2430,bg=default"
set -g pane-active-border-style "fg=#5c6773,bg=default"

# reload
bind-key r source-file ~/.tmux.conf \; display "Reloaded"

# session mgmt
set -g detach-on-destroy off
bind-key s choose-tree -Zs
bind-key n command-prompt -p "new session:" "new-session -s '%%'"

# window and pane mgmt
bind-key l split-window -h -c "#{pane_current_path}"
bind-key j split-window -v -c "#{pane_current_path}"
bind-key t new-window -c "#{pane_current_path}"
bind-key -r ] next-window
bind-key -n M-] next-window
bind-key -r [ previous-window
bind-key -n M-[ previous-window
bind-key f resize-pane -Z
bind-key -r = resize-pane -R 5
bind-key -r - resize-pane -L 5
bind-key -n S-Left  swap-window -d -t -1
bind-key -n S-Right swap-window -d -t +1
bind-key -n M-k select-pane -U
bind-key -n M-j select-pane -D
bind-key -n M-h select-pane -L
bind-key -n M-l select-pane -R
bind-key w kill-pane
bind-key q kill-window

# project switcher
bind-key p display-popup -E "tmux-sessionizer"
bind-key -n M-p display-popup -E "tmux-sessionizer"

# yazi
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM
